export interface Patient {
  id: number;
  name: string;
  lastSeenDate: Date;
  lastSeenReason: string;
  followUpScheduled: boolean;
  careStatus: "standard" | "monitor" | "high risk";
}

export const patientList: Patient[] = [
  {
    id: 1,
    name: "Liam Carter",
    lastSeenDate: new Date("2024-02-10"),
    lastSeenReason: "Routine checkup",
    followUpScheduled: false,
    careStatus: "standard",
  },
  {
    id: 2,
    name: "Sophia Reynolds",
    lastSeenDate: new Date("2024-02-05"),
    lastSeenReason: "Flu symptoms",
    followUpScheduled: true,
    careStatus: "monitor",
  },
  {
    id: 3,
    name: "Ethan Bennett",
    lastSeenDate: new Date("2024-02-12"),
    lastSeenReason: "Post-surgery follow-up",
    followUpScheduled: true,
    careStatus: "high risk",
  },
  {
    id: 4,
    name: "Olivia Hayes",
    lastSeenDate: new Date("2024-01-30"),
    lastSeenReason: "Blood pressure check",
    followUpScheduled: false,
    careStatus: "standard",
  },
  {
    id: 5,
    name: "Mason Brooks",
    lastSeenDate: new Date("2024-02-08"),
    lastSeenReason: "Annual physical",
    followUpScheduled: false,
    careStatus: "standard",
  },
  {
    id: 6,
    name: "Ava Mitchell",
    lastSeenDate: new Date("2024-02-14"),
    lastSeenReason: "Diabetes management",
    followUpScheduled: true,
    careStatus: "monitor",
  },
  {
    id: 7,
    name: "Lucas Foster",
    lastSeenDate: new Date("2024-02-01"),
    lastSeenReason: "Neurology consult",
    followUpScheduled: true,
    careStatus: "high risk",
  },
  {
    id: 8,
    name: "Harper Collins",
    lastSeenDate: new Date("2024-02-11"),
    lastSeenReason: "Medication review",
    followUpScheduled: false,
    careStatus: "monitor",
  },
  {
    id: 9,
    name: "Noah Griffin",
    lastSeenDate: new Date("2024-02-03"),
    lastSeenReason: "Stress test",
    followUpScheduled: false,
    careStatus: "standard",
  },
  {
    id: 10,
    name: "Emma Sullivan",
    lastSeenDate: new Date("2024-02-09"),
    lastSeenReason: "Physical therapy",
    followUpScheduled: true,
    careStatus: "monitor",
  },
  {
    id: 11,
    name: "James Parker",
    lastSeenDate: new Date("2024-02-07"),
    lastSeenReason: "Fracture follow-up",
    followUpScheduled: true,
    careStatus: "high risk",
  },
  {
    id: 12,
    name: "Isabella Reed",
    lastSeenDate: new Date("2024-02-06"),
    lastSeenReason: "Vision screening",
    followUpScheduled: false,
    careStatus: "standard",
  },
  {
    id: 13,
    name: "Benjamin Cooper",
    lastSeenDate: new Date("2024-02-02"),
    lastSeenReason: "Allergy testing",
    followUpScheduled: true,
    careStatus: "monitor",
  },
  {
    id: 14,
    name: "Charlotte Edwards",
    lastSeenDate: new Date("2024-01-28"),
    lastSeenReason: "Dermatology consult",
    followUpScheduled: false,
    careStatus: "standard",
  },
  {
    id: 15,
    name: "William Turner",
    lastSeenDate: new Date("2024-02-13"),
    lastSeenReason: "Work-related stress",
    followUpScheduled: true,
    careStatus: "high risk",
  },
  {
    id: 16,
    name: "Amelia Ross",
    lastSeenDate: new Date("2024-02-04"),
    lastSeenReason: "Sleep disorder consultation",
    followUpScheduled: true,
    careStatus: "monitor",
  },
  {
    id: 17,
    name: "Henry Hughes",
    lastSeenDate: new Date("2024-02-10"),
    lastSeenReason: "Cardiac assessment",
    followUpScheduled: false,
    careStatus: "high risk",
  },
  {
    id: 18,
    name: "Mia Price",
    lastSeenDate: new Date("2024-02-15"),
    lastSeenReason: "Pregnancy checkup",
    followUpScheduled: true,
    careStatus: "monitor",
  },
  {
    id: 19,
    name: "Alexander Rivera",
    lastSeenDate: new Date("2024-02-12"),
    lastSeenReason: "Hearing test",
    followUpScheduled: false,
    careStatus: "standard",
  },
];
